#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AdopcionMascotasDB1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAdopcionesAprobadas(AdopcionesAprobadas instance);
    partial void UpdateAdopcionesAprobadas(AdopcionesAprobadas instance);
    partial void DeleteAdopcionesAprobadas(AdopcionesAprobadas instance);
    partial void InsertCategorias(Categorias instance);
    partial void UpdateCategorias(Categorias instance);
    partial void DeleteCategorias(Categorias instance);
    partial void InsertDonantes(Donantes instance);
    partial void UpdateDonantes(Donantes instance);
    partial void DeleteDonantes(Donantes instance);
    partial void InsertFotosMascotas(FotosMascotas instance);
    partial void UpdateFotosMascotas(FotosMascotas instance);
    partial void DeleteFotosMascotas(FotosMascotas instance);
    partial void InsertFotosReportesPerdidos(FotosReportesPerdidos instance);
    partial void UpdateFotosReportesPerdidos(FotosReportesPerdidos instance);
    partial void DeleteFotosReportesPerdidos(FotosReportesPerdidos instance);
    partial void InsertRazas(Razas instance);
    partial void UpdateRazas(Razas instance);
    partial void DeleteRazas(Razas instance);
    partial void InsertMascotas(Mascotas instance);
    partial void UpdateMascotas(Mascotas instance);
    partial void DeleteMascotas(Mascotas instance);
    partial void InsertRefugios(Refugios instance);
    partial void UpdateRefugios(Refugios instance);
    partial void DeleteRefugios(Refugios instance);
    partial void InsertReportesPerdidos(ReportesPerdidos instance);
    partial void UpdateReportesPerdidos(ReportesPerdidos instance);
    partial void DeleteReportesPerdidos(ReportesPerdidos instance);
    partial void InsertSolicitudesAdopcion(SolicitudesAdopcion instance);
    partial void UpdateSolicitudesAdopcion(SolicitudesAdopcion instance);
    partial void DeleteSolicitudesAdopcion(SolicitudesAdopcion instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void InsertVacunas(Vacunas instance);
    partial void UpdateVacunas(Vacunas instance);
    partial void DeleteVacunas(Vacunas instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.AdopcionMascotasDB1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AdopcionesAprobadas> AdopcionesAprobadas
		{
			get
			{
				return this.GetTable<AdopcionesAprobadas>();
			}
		}
		
		public System.Data.Linq.Table<Categorias> Categorias
		{
			get
			{
				return this.GetTable<Categorias>();
			}
		}
		
		public System.Data.Linq.Table<Donantes> Donantes
		{
			get
			{
				return this.GetTable<Donantes>();
			}
		}
		
		public System.Data.Linq.Table<FotosMascotas> FotosMascotas
		{
			get
			{
				return this.GetTable<FotosMascotas>();
			}
		}
		
		public System.Data.Linq.Table<FotosReportesPerdidos> FotosReportesPerdidos
		{
			get
			{
				return this.GetTable<FotosReportesPerdidos>();
			}
		}
		
		public System.Data.Linq.Table<Razas> Razas
		{
			get
			{
				return this.GetTable<Razas>();
			}
		}
		
		public System.Data.Linq.Table<Mascotas> Mascotas
		{
			get
			{
				return this.GetTable<Mascotas>();
			}
		}
		
		public System.Data.Linq.Table<Refugios> Refugios
		{
			get
			{
				return this.GetTable<Refugios>();
			}
		}
		
		public System.Data.Linq.Table<ReportesPerdidos> ReportesPerdidos
		{
			get
			{
				return this.GetTable<ReportesPerdidos>();
			}
		}
		
		public System.Data.Linq.Table<SolicitudesAdopcion> SolicitudesAdopcion
		{
			get
			{
				return this.GetTable<SolicitudesAdopcion>();
			}
		}

        public Table<Usuarios> GetUsuarios()
        {
            return this.GetTable<Usuarios>();
        }

        public System.Data.Linq.Table<Vacunas> Vacunas
		{
			get
			{
				return this.GetTable<Vacunas>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdopcionesAprobadas")]
	public partial class AdopcionesAprobadas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AdopcionID;
		
		private int _UsuarioID;
		
		private int _MascotaID;
		
		private System.DateTime _FechaAdopcion;
		
		private EntityRef<Mascotas> _Mascotas;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdopcionIDChanging(int value);
    partial void OnAdopcionIDChanged();
    partial void OnUsuarioIDChanging(int value);
    partial void OnUsuarioIDChanged();
    partial void OnMascotaIDChanging(int value);
    partial void OnMascotaIDChanged();
    partial void OnFechaAdopcionChanging(System.DateTime value);
    partial void OnFechaAdopcionChanged();
    #endregion
		
		public AdopcionesAprobadas()
		{
			this._Mascotas = default(EntityRef<Mascotas>);
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdopcionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AdopcionID
		{
			get
			{
				return this._AdopcionID;
			}
			set
			{
				if ((this._AdopcionID != value))
				{
					this.OnAdopcionIDChanging(value);
					this.SendPropertyChanging();
					this._AdopcionID = value;
					this.SendPropertyChanged("AdopcionID");
					this.OnAdopcionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="Int NOT NULL")]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._UsuarioID = value;
					this.SendPropertyChanged("UsuarioID");
					this.OnUsuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MascotaID", DbType="Int NOT NULL")]
		public int MascotaID
		{
			get
			{
				return this._MascotaID;
			}
			set
			{
				if ((this._MascotaID != value))
				{
					if (this._Mascotas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMascotaIDChanging(value);
					this.SendPropertyChanging();
					this._MascotaID = value;
					this.SendPropertyChanged("MascotaID");
					this.OnMascotaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdopcion", DbType="Date NOT NULL")]
		public System.DateTime FechaAdopcion
		{
			get
			{
				return this._FechaAdopcion;
			}
			set
			{
				if ((this._FechaAdopcion != value))
				{
					this.OnFechaAdopcionChanging(value);
					this.SendPropertyChanging();
					this._FechaAdopcion = value;
					this.SendPropertyChanged("FechaAdopcion");
					this.OnFechaAdopcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mascotas_AdopcionesAprobadas", Storage="_Mascotas", ThisKey="MascotaID", OtherKey="MascotaID", IsForeignKey=true)]
		public Mascotas Mascotas
		{
			get
			{
				return this._Mascotas.Entity;
			}
			set
			{
				Mascotas previousValue = this._Mascotas.Entity;
				if (((previousValue != value) 
							|| (this._Mascotas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mascotas.Entity = null;
						previousValue.AdopcionesAprobadas.Remove(this);
					}
					this._Mascotas.Entity = value;
					if ((value != null))
					{
						value.AdopcionesAprobadas.Add(this);
						this._MascotaID = value.MascotaID;
					}
					else
					{
						this._MascotaID = default(int);
					}
					this.SendPropertyChanged("Mascotas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_AdopcionesAprobadas", Storage="_Usuarios", ThisKey="UsuarioID", OtherKey="UsuarioID", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.AdopcionesAprobadas.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.AdopcionesAprobadas.Add(this);
						this._UsuarioID = value.UsuarioID;
					}
					else
					{
						this._UsuarioID = default(int);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categorias")]
	public partial class Categorias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategoriaID;
		
		private string _Nombre;
		
		private EntitySet<Razas> _Razas;
		
		private EntitySet<Mascotas> _Mascotas;
		
		private EntitySet<ReportesPerdidos> _ReportesPerdidos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoriaIDChanging(int value);
    partial void OnCategoriaIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Categorias()
		{
			this._Razas = new EntitySet<Razas>(new Action<Razas>(this.attach_Razas), new Action<Razas>(this.detach_Razas));
			this._Mascotas = new EntitySet<Mascotas>(new Action<Mascotas>(this.attach_Mascotas), new Action<Mascotas>(this.detach_Mascotas));
			this._ReportesPerdidos = new EntitySet<ReportesPerdidos>(new Action<ReportesPerdidos>(this.attach_ReportesPerdidos), new Action<ReportesPerdidos>(this.detach_ReportesPerdidos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategoriaID
		{
			get
			{
				return this._CategoriaID;
			}
			set
			{
				if ((this._CategoriaID != value))
				{
					this.OnCategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._CategoriaID = value;
					this.SendPropertyChanged("CategoriaID");
					this.OnCategoriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorias_Razas", Storage="_Razas", ThisKey="CategoriaID", OtherKey="CategoriaID")]
		public EntitySet<Razas> Razas
		{
			get
			{
				return this._Razas;
			}
			set
			{
				this._Razas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorias_Mascotas", Storage="_Mascotas", ThisKey="CategoriaID", OtherKey="CategoriaID")]
		public EntitySet<Mascotas> Mascotas
		{
			get
			{
				return this._Mascotas;
			}
			set
			{
				this._Mascotas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorias_ReportesPerdidos", Storage="_ReportesPerdidos", ThisKey="CategoriaID", OtherKey="CategoriaID")]
		public EntitySet<ReportesPerdidos> ReportesPerdidos
		{
			get
			{
				return this._ReportesPerdidos;
			}
			set
			{
				this._ReportesPerdidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Razas(Razas entity)
		{
			this.SendPropertyChanging();
			entity.Categorias = this;
		}
		
		private void detach_Razas(Razas entity)
		{
			this.SendPropertyChanging();
			entity.Categorias = null;
		}
		
		private void attach_Mascotas(Mascotas entity)
		{
			this.SendPropertyChanging();
			entity.Categorias = this;
		}
		
		private void detach_Mascotas(Mascotas entity)
		{
			this.SendPropertyChanging();
			entity.Categorias = null;
		}
		
		private void attach_ReportesPerdidos(ReportesPerdidos entity)
		{
			this.SendPropertyChanging();
			entity.Categorias = this;
		}
		
		private void detach_ReportesPerdidos(ReportesPerdidos entity)
		{
			this.SendPropertyChanging();
			entity.Categorias = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Donantes")]
	public partial class Donantes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DonanteID;
		
		private string _Nombre;
		
		private string _Email;
		
		private string _Telefono;
		
		private string _Mensaje;
		
		private System.DateTime _FechaDonacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDonanteIDChanging(int value);
    partial void OnDonanteIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnMensajeChanging(string value);
    partial void OnMensajeChanged();
    partial void OnFechaDonacionChanging(System.DateTime value);
    partial void OnFechaDonacionChanged();
    #endregion
		
		public Donantes()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonanteID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DonanteID
		{
			get
			{
				return this._DonanteID;
			}
			set
			{
				if ((this._DonanteID != value))
				{
					this.OnDonanteIDChanging(value);
					this.SendPropertyChanging();
					this._DonanteID = value;
					this.SendPropertyChanged("DonanteID");
					this.OnDonanteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this.OnMensajeChanging(value);
					this.SendPropertyChanging();
					this._Mensaje = value;
					this.SendPropertyChanged("Mensaje");
					this.OnMensajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDonacion", DbType="Date NOT NULL")]
		public System.DateTime FechaDonacion
		{
			get
			{
				return this._FechaDonacion;
			}
			set
			{
				if ((this._FechaDonacion != value))
				{
					this.OnFechaDonacionChanging(value);
					this.SendPropertyChanging();
					this._FechaDonacion = value;
					this.SendPropertyChanged("FechaDonacion");
					this.OnFechaDonacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FotosMascotas")]
	public partial class FotosMascotas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FotoID;
		
		private int _MascotaID;
		
		private System.Data.Linq.Binary _Foto;
		
		private EntityRef<Mascotas> _Mascotas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFotoIDChanging(int value);
    partial void OnFotoIDChanged();
    partial void OnMascotaIDChanging(int value);
    partial void OnMascotaIDChanged();
    partial void OnFotoChanging(System.Data.Linq.Binary value);
    partial void OnFotoChanged();
    #endregion
		
		public FotosMascotas()
		{
			this._Mascotas = default(EntityRef<Mascotas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FotoID
		{
			get
			{
				return this._FotoID;
			}
			set
			{
				if ((this._FotoID != value))
				{
					this.OnFotoIDChanging(value);
					this.SendPropertyChanging();
					this._FotoID = value;
					this.SendPropertyChanged("FotoID");
					this.OnFotoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MascotaID", DbType="Int NOT NULL")]
		public int MascotaID
		{
			get
			{
				return this._MascotaID;
			}
			set
			{
				if ((this._MascotaID != value))
				{
					if (this._Mascotas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMascotaIDChanging(value);
					this.SendPropertyChanging();
					this._MascotaID = value;
					this.SendPropertyChanged("MascotaID");
					this.OnMascotaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mascotas_FotosMascotas", Storage="_Mascotas", ThisKey="MascotaID", OtherKey="MascotaID", IsForeignKey=true)]
		public Mascotas Mascotas
		{
			get
			{
				return this._Mascotas.Entity;
			}
			set
			{
				Mascotas previousValue = this._Mascotas.Entity;
				if (((previousValue != value) 
							|| (this._Mascotas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mascotas.Entity = null;
						previousValue.FotosMascotas.Remove(this);
					}
					this._Mascotas.Entity = value;
					if ((value != null))
					{
						value.FotosMascotas.Add(this);
						this._MascotaID = value.MascotaID;
					}
					else
					{
						this._MascotaID = default(int);
					}
					this.SendPropertyChanged("Mascotas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FotosReportesPerdidos")]
	public partial class FotosReportesPerdidos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FotoID;
		
		private int _ReporteID;
		
		private System.Data.Linq.Binary _Foto;
		
		private EntityRef<ReportesPerdidos> _ReportesPerdidos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFotoIDChanging(int value);
    partial void OnFotoIDChanged();
    partial void OnReporteIDChanging(int value);
    partial void OnReporteIDChanged();
    partial void OnFotoChanging(System.Data.Linq.Binary value);
    partial void OnFotoChanged();
    #endregion
		
		public FotosReportesPerdidos()
		{
			this._ReportesPerdidos = default(EntityRef<ReportesPerdidos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FotoID
		{
			get
			{
				return this._FotoID;
			}
			set
			{
				if ((this._FotoID != value))
				{
					this.OnFotoIDChanging(value);
					this.SendPropertyChanging();
					this._FotoID = value;
					this.SendPropertyChanged("FotoID");
					this.OnFotoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReporteID", DbType="Int NOT NULL")]
		public int ReporteID
		{
			get
			{
				return this._ReporteID;
			}
			set
			{
				if ((this._ReporteID != value))
				{
					if (this._ReportesPerdidos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnReporteIDChanging(value);
					this.SendPropertyChanging();
					this._ReporteID = value;
					this.SendPropertyChanged("ReporteID");
					this.OnReporteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ReportesPerdidos_FotosReportesPerdidos", Storage="_ReportesPerdidos", ThisKey="ReporteID", OtherKey="ReporteID", IsForeignKey=true)]
		public ReportesPerdidos ReportesPerdidos
		{
			get
			{
				return this._ReportesPerdidos.Entity;
			}
			set
			{
				ReportesPerdidos previousValue = this._ReportesPerdidos.Entity;
				if (((previousValue != value) 
							|| (this._ReportesPerdidos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ReportesPerdidos.Entity = null;
						previousValue.FotosReportesPerdidos.Remove(this);
					}
					this._ReportesPerdidos.Entity = value;
					if ((value != null))
					{
						value.FotosReportesPerdidos.Add(this);
						this._ReporteID = value.ReporteID;
					}
					else
					{
						this._ReporteID = default(int);
					}
					this.SendPropertyChanged("ReportesPerdidos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Razas")]
	public partial class Razas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RazaID;
		
		private string _Nombre;
		
		private int _CategoriaID;
		
		private EntitySet<Mascotas> _Mascotas;
		
		private EntitySet<ReportesPerdidos> _ReportesPerdidos;
		
		private EntityRef<Categorias> _Categorias;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRazaIDChanging(int value);
    partial void OnRazaIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCategoriaIDChanging(int value);
    partial void OnCategoriaIDChanged();
    #endregion
		
		public Razas()
		{
			this._Mascotas = new EntitySet<Mascotas>(new Action<Mascotas>(this.attach_Mascotas), new Action<Mascotas>(this.detach_Mascotas));
			this._ReportesPerdidos = new EntitySet<ReportesPerdidos>(new Action<ReportesPerdidos>(this.attach_ReportesPerdidos), new Action<ReportesPerdidos>(this.detach_ReportesPerdidos));
			this._Categorias = default(EntityRef<Categorias>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RazaID
		{
			get
			{
				return this._RazaID;
			}
			set
			{
				if ((this._RazaID != value))
				{
					this.OnRazaIDChanging(value);
					this.SendPropertyChanging();
					this._RazaID = value;
					this.SendPropertyChanged("RazaID");
					this.OnRazaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaID", DbType="Int NOT NULL")]
		public int CategoriaID
		{
			get
			{
				return this._CategoriaID;
			}
			set
			{
				if ((this._CategoriaID != value))
				{
					if (this._Categorias.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._CategoriaID = value;
					this.SendPropertyChanged("CategoriaID");
					this.OnCategoriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Razas_Mascotas", Storage="_Mascotas", ThisKey="RazaID", OtherKey="RazaID")]
		public EntitySet<Mascotas> Mascotas
		{
			get
			{
				return this._Mascotas;
			}
			set
			{
				this._Mascotas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Razas_ReportesPerdidos", Storage="_ReportesPerdidos", ThisKey="RazaID", OtherKey="RazaID")]
		public EntitySet<ReportesPerdidos> ReportesPerdidos
		{
			get
			{
				return this._ReportesPerdidos;
			}
			set
			{
				this._ReportesPerdidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorias_Razas", Storage="_Categorias", ThisKey="CategoriaID", OtherKey="CategoriaID", IsForeignKey=true)]
		public Categorias Categorias
		{
			get
			{
				return this._Categorias.Entity;
			}
			set
			{
				Categorias previousValue = this._Categorias.Entity;
				if (((previousValue != value) 
							|| (this._Categorias.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categorias.Entity = null;
						previousValue.Razas.Remove(this);
					}
					this._Categorias.Entity = value;
					if ((value != null))
					{
						value.Razas.Add(this);
						this._CategoriaID = value.CategoriaID;
					}
					else
					{
						this._CategoriaID = default(int);
					}
					this.SendPropertyChanged("Categorias");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Mascotas(Mascotas entity)
		{
			this.SendPropertyChanging();
			entity.Razas = this;
		}
		
		private void detach_Mascotas(Mascotas entity)
		{
			this.SendPropertyChanging();
			entity.Razas = null;
		}
		
		private void attach_ReportesPerdidos(ReportesPerdidos entity)
		{
			this.SendPropertyChanging();
			entity.Razas = this;
		}
		
		private void detach_ReportesPerdidos(ReportesPerdidos entity)
		{
			this.SendPropertyChanging();
			entity.Razas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mascotas")]
	public partial class Mascotas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MascotaID;
		
		private string _Nombre;
		
		private int _CategoriaID;
		
		private int _RazaID;
		
		private string _Descripcion;
		
		private string _Caracteristicas;
		
		private string _Estado;
		
		private System.Nullable<System.DateTime> _FechaAdopcion;
		
		private System.Nullable<System.DateTime> _FechaEncontrado;
		
		private EntitySet<AdopcionesAprobadas> _AdopcionesAprobadas;
		
		private EntitySet<FotosMascotas> _FotosMascotas;
		
		private EntitySet<SolicitudesAdopcion> _SolicitudesAdopcion;
		
		private EntitySet<Vacunas> _Vacunas;
		
		private EntityRef<Categorias> _Categorias;
		
		private EntityRef<Razas> _Razas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMascotaIDChanging(int value);
    partial void OnMascotaIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCategoriaIDChanging(int value);
    partial void OnCategoriaIDChanged();
    partial void OnRazaIDChanging(int value);
    partial void OnRazaIDChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnCaracteristicasChanging(string value);
    partial void OnCaracteristicasChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnFechaAdopcionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaAdopcionChanged();
    partial void OnFechaEncontradoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaEncontradoChanged();
    #endregion
		
		public Mascotas()
		{
			this._AdopcionesAprobadas = new EntitySet<AdopcionesAprobadas>(new Action<AdopcionesAprobadas>(this.attach_AdopcionesAprobadas), new Action<AdopcionesAprobadas>(this.detach_AdopcionesAprobadas));
			this._FotosMascotas = new EntitySet<FotosMascotas>(new Action<FotosMascotas>(this.attach_FotosMascotas), new Action<FotosMascotas>(this.detach_FotosMascotas));
			this._SolicitudesAdopcion = new EntitySet<SolicitudesAdopcion>(new Action<SolicitudesAdopcion>(this.attach_SolicitudesAdopcion), new Action<SolicitudesAdopcion>(this.detach_SolicitudesAdopcion));
			this._Vacunas = new EntitySet<Vacunas>(new Action<Vacunas>(this.attach_Vacunas), new Action<Vacunas>(this.detach_Vacunas));
			this._Categorias = default(EntityRef<Categorias>);
			this._Razas = default(EntityRef<Razas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MascotaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MascotaID
		{
			get
			{
				return this._MascotaID;
			}
			set
			{
				if ((this._MascotaID != value))
				{
					this.OnMascotaIDChanging(value);
					this.SendPropertyChanging();
					this._MascotaID = value;
					this.SendPropertyChanged("MascotaID");
					this.OnMascotaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaID", DbType="Int NOT NULL")]
		public int CategoriaID
		{
			get
			{
				return this._CategoriaID;
			}
			set
			{
				if ((this._CategoriaID != value))
				{
					if (this._Categorias.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._CategoriaID = value;
					this.SendPropertyChanged("CategoriaID");
					this.OnCategoriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazaID", DbType="Int NOT NULL")]
		public int RazaID
		{
			get
			{
				return this._RazaID;
			}
			set
			{
				if ((this._RazaID != value))
				{
					if (this._Razas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRazaIDChanging(value);
					this.SendPropertyChanging();
					this._RazaID = value;
					this.SendPropertyChanged("RazaID");
					this.OnRazaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caracteristicas", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Caracteristicas
		{
			get
			{
				return this._Caracteristicas;
			}
			set
			{
				if ((this._Caracteristicas != value))
				{
					this.OnCaracteristicasChanging(value);
					this.SendPropertyChanging();
					this._Caracteristicas = value;
					this.SendPropertyChanged("Caracteristicas");
					this.OnCaracteristicasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdopcion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdopcion
		{
			get
			{
				return this._FechaAdopcion;
			}
			set
			{
				if ((this._FechaAdopcion != value))
				{
					this.OnFechaAdopcionChanging(value);
					this.SendPropertyChanging();
					this._FechaAdopcion = value;
					this.SendPropertyChanged("FechaAdopcion");
					this.OnFechaAdopcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEncontrado", DbType="Date")]
		public System.Nullable<System.DateTime> FechaEncontrado
		{
			get
			{
				return this._FechaEncontrado;
			}
			set
			{
				if ((this._FechaEncontrado != value))
				{
					this.OnFechaEncontradoChanging(value);
					this.SendPropertyChanging();
					this._FechaEncontrado = value;
					this.SendPropertyChanged("FechaEncontrado");
					this.OnFechaEncontradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mascotas_AdopcionesAprobadas", Storage="_AdopcionesAprobadas", ThisKey="MascotaID", OtherKey="MascotaID")]
		public EntitySet<AdopcionesAprobadas> AdopcionesAprobadas
		{
			get
			{
				return this._AdopcionesAprobadas;
			}
			set
			{
				this._AdopcionesAprobadas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mascotas_FotosMascotas", Storage="_FotosMascotas", ThisKey="MascotaID", OtherKey="MascotaID")]
		public EntitySet<FotosMascotas> FotosMascotas
		{
			get
			{
				return this._FotosMascotas;
			}
			set
			{
				this._FotosMascotas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mascotas_SolicitudesAdopcion", Storage="_SolicitudesAdopcion", ThisKey="MascotaID", OtherKey="MascotaID")]
		public EntitySet<SolicitudesAdopcion> SolicitudesAdopcion
		{
			get
			{
				return this._SolicitudesAdopcion;
			}
			set
			{
				this._SolicitudesAdopcion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mascotas_Vacunas", Storage="_Vacunas", ThisKey="MascotaID", OtherKey="MascotaID")]
		public EntitySet<Vacunas> Vacunas
		{
			get
			{
				return this._Vacunas;
			}
			set
			{
				this._Vacunas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorias_Mascotas", Storage="_Categorias", ThisKey="CategoriaID", OtherKey="CategoriaID", IsForeignKey=true)]
		public Categorias Categorias
		{
			get
			{
				return this._Categorias.Entity;
			}
			set
			{
				Categorias previousValue = this._Categorias.Entity;
				if (((previousValue != value) 
							|| (this._Categorias.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categorias.Entity = null;
						previousValue.Mascotas.Remove(this);
					}
					this._Categorias.Entity = value;
					if ((value != null))
					{
						value.Mascotas.Add(this);
						this._CategoriaID = value.CategoriaID;
					}
					else
					{
						this._CategoriaID = default(int);
					}
					this.SendPropertyChanged("Categorias");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Razas_Mascotas", Storage="_Razas", ThisKey="RazaID", OtherKey="RazaID", IsForeignKey=true)]
		public Razas Razas
		{
			get
			{
				return this._Razas.Entity;
			}
			set
			{
				Razas previousValue = this._Razas.Entity;
				if (((previousValue != value) 
							|| (this._Razas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Razas.Entity = null;
						previousValue.Mascotas.Remove(this);
					}
					this._Razas.Entity = value;
					if ((value != null))
					{
						value.Mascotas.Add(this);
						this._RazaID = value.RazaID;
					}
					else
					{
						this._RazaID = default(int);
					}
					this.SendPropertyChanged("Razas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AdopcionesAprobadas(AdopcionesAprobadas entity)
		{
			this.SendPropertyChanging();
			entity.Mascotas = this;
		}
		
		private void detach_AdopcionesAprobadas(AdopcionesAprobadas entity)
		{
			this.SendPropertyChanging();
			entity.Mascotas = null;
		}
		
		private void attach_FotosMascotas(FotosMascotas entity)
		{
			this.SendPropertyChanging();
			entity.Mascotas = this;
		}
		
		private void detach_FotosMascotas(FotosMascotas entity)
		{
			this.SendPropertyChanging();
			entity.Mascotas = null;
		}
		
		private void attach_SolicitudesAdopcion(SolicitudesAdopcion entity)
		{
			this.SendPropertyChanging();
			entity.Mascotas = this;
		}
		
		private void detach_SolicitudesAdopcion(SolicitudesAdopcion entity)
		{
			this.SendPropertyChanging();
			entity.Mascotas = null;
		}
		
		private void attach_Vacunas(Vacunas entity)
		{
			this.SendPropertyChanging();
			entity.Mascotas = this;
		}
		
		private void detach_Vacunas(Vacunas entity)
		{
			this.SendPropertyChanging();
			entity.Mascotas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Refugios")]
	public partial class Refugios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RefugioID;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Email;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRefugioIDChanging(int value);
    partial void OnRefugioIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Refugios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefugioID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RefugioID
		{
			get
			{
				return this._RefugioID;
			}
			set
			{
				if ((this._RefugioID != value))
				{
					this.OnRefugioIDChanging(value);
					this.SendPropertyChanging();
					this._RefugioID = value;
					this.SendPropertyChanged("RefugioID");
					this.OnRefugioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportesPerdidos")]
	public partial class ReportesPerdidos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ReporteID;
		
		private int _ReporterUsuarioID;
		
		private System.Nullable<int> _FinderUsuarioID;
		
		private string _NombreMascota;
		
		private int _CategoriaID;
		
		private int _RazaID;
		
		private string _Caracteristicas;
		
		private string _ComoPerdio;
		
		private System.DateTime _FechaReporte;
		
		private string _Estado;
		
		private System.Nullable<System.DateTime> _FechaEncontrado;
		
		private EntitySet<FotosReportesPerdidos> _FotosReportesPerdidos;
		
		private EntityRef<Categorias> _Categorias;
		
		private EntityRef<Razas> _Razas;
		
		private EntityRef<Usuarios> _Usuarios;
		
		private EntityRef<Usuarios> _Usuarios1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReporteIDChanging(int value);
    partial void OnReporteIDChanged();
    partial void OnReporterUsuarioIDChanging(int value);
    partial void OnReporterUsuarioIDChanged();
    partial void OnFinderUsuarioIDChanging(System.Nullable<int> value);
    partial void OnFinderUsuarioIDChanged();
    partial void OnNombreMascotaChanging(string value);
    partial void OnNombreMascotaChanged();
    partial void OnCategoriaIDChanging(int value);
    partial void OnCategoriaIDChanged();
    partial void OnRazaIDChanging(int value);
    partial void OnRazaIDChanged();
    partial void OnCaracteristicasChanging(string value);
    partial void OnCaracteristicasChanged();
    partial void OnComoPerdioChanging(string value);
    partial void OnComoPerdioChanged();
    partial void OnFechaReporteChanging(System.DateTime value);
    partial void OnFechaReporteChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnFechaEncontradoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaEncontradoChanged();
    #endregion
		
		public ReportesPerdidos()
		{
			this._FotosReportesPerdidos = new EntitySet<FotosReportesPerdidos>(new Action<FotosReportesPerdidos>(this.attach_FotosReportesPerdidos), new Action<FotosReportesPerdidos>(this.detach_FotosReportesPerdidos));
			this._Categorias = default(EntityRef<Categorias>);
			this._Razas = default(EntityRef<Razas>);
			this._Usuarios = default(EntityRef<Usuarios>);
			this._Usuarios1 = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReporteID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ReporteID
		{
			get
			{
				return this._ReporteID;
			}
			set
			{
				if ((this._ReporteID != value))
				{
					this.OnReporteIDChanging(value);
					this.SendPropertyChanging();
					this._ReporteID = value;
					this.SendPropertyChanged("ReporteID");
					this.OnReporteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReporterUsuarioID", DbType="Int NOT NULL")]
		public int ReporterUsuarioID
		{
			get
			{
				return this._ReporterUsuarioID;
			}
			set
			{
				if ((this._ReporterUsuarioID != value))
				{
					if (this._Usuarios1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnReporterUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._ReporterUsuarioID = value;
					this.SendPropertyChanged("ReporterUsuarioID");
					this.OnReporterUsuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinderUsuarioID", DbType="Int")]
		public System.Nullable<int> FinderUsuarioID
		{
			get
			{
				return this._FinderUsuarioID;
			}
			set
			{
				if ((this._FinderUsuarioID != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFinderUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._FinderUsuarioID = value;
					this.SendPropertyChanged("FinderUsuarioID");
					this.OnFinderUsuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreMascota", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreMascota
		{
			get
			{
				return this._NombreMascota;
			}
			set
			{
				if ((this._NombreMascota != value))
				{
					this.OnNombreMascotaChanging(value);
					this.SendPropertyChanging();
					this._NombreMascota = value;
					this.SendPropertyChanged("NombreMascota");
					this.OnNombreMascotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaID", DbType="Int NOT NULL")]
		public int CategoriaID
		{
			get
			{
				return this._CategoriaID;
			}
			set
			{
				if ((this._CategoriaID != value))
				{
					if (this._Categorias.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._CategoriaID = value;
					this.SendPropertyChanged("CategoriaID");
					this.OnCategoriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazaID", DbType="Int NOT NULL")]
		public int RazaID
		{
			get
			{
				return this._RazaID;
			}
			set
			{
				if ((this._RazaID != value))
				{
					if (this._Razas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRazaIDChanging(value);
					this.SendPropertyChanging();
					this._RazaID = value;
					this.SendPropertyChanged("RazaID");
					this.OnRazaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caracteristicas", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Caracteristicas
		{
			get
			{
				return this._Caracteristicas;
			}
			set
			{
				if ((this._Caracteristicas != value))
				{
					this.OnCaracteristicasChanging(value);
					this.SendPropertyChanging();
					this._Caracteristicas = value;
					this.SendPropertyChanged("Caracteristicas");
					this.OnCaracteristicasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComoPerdio", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ComoPerdio
		{
			get
			{
				return this._ComoPerdio;
			}
			set
			{
				if ((this._ComoPerdio != value))
				{
					this.OnComoPerdioChanging(value);
					this.SendPropertyChanging();
					this._ComoPerdio = value;
					this.SendPropertyChanged("ComoPerdio");
					this.OnComoPerdioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaReporte", DbType="Date NOT NULL")]
		public System.DateTime FechaReporte
		{
			get
			{
				return this._FechaReporte;
			}
			set
			{
				if ((this._FechaReporte != value))
				{
					this.OnFechaReporteChanging(value);
					this.SendPropertyChanging();
					this._FechaReporte = value;
					this.SendPropertyChanged("FechaReporte");
					this.OnFechaReporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEncontrado", DbType="Date")]
		public System.Nullable<System.DateTime> FechaEncontrado
		{
			get
			{
				return this._FechaEncontrado;
			}
			set
			{
				if ((this._FechaEncontrado != value))
				{
					this.OnFechaEncontradoChanging(value);
					this.SendPropertyChanging();
					this._FechaEncontrado = value;
					this.SendPropertyChanged("FechaEncontrado");
					this.OnFechaEncontradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ReportesPerdidos_FotosReportesPerdidos", Storage="_FotosReportesPerdidos", ThisKey="ReporteID", OtherKey="ReporteID")]
		public EntitySet<FotosReportesPerdidos> FotosReportesPerdidos
		{
			get
			{
				return this._FotosReportesPerdidos;
			}
			set
			{
				this._FotosReportesPerdidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorias_ReportesPerdidos", Storage="_Categorias", ThisKey="CategoriaID", OtherKey="CategoriaID", IsForeignKey=true)]
		public Categorias Categorias
		{
			get
			{
				return this._Categorias.Entity;
			}
			set
			{
				Categorias previousValue = this._Categorias.Entity;
				if (((previousValue != value) 
							|| (this._Categorias.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categorias.Entity = null;
						previousValue.ReportesPerdidos.Remove(this);
					}
					this._Categorias.Entity = value;
					if ((value != null))
					{
						value.ReportesPerdidos.Add(this);
						this._CategoriaID = value.CategoriaID;
					}
					else
					{
						this._CategoriaID = default(int);
					}
					this.SendPropertyChanged("Categorias");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Razas_ReportesPerdidos", Storage="_Razas", ThisKey="RazaID", OtherKey="RazaID", IsForeignKey=true)]
		public Razas Razas
		{
			get
			{
				return this._Razas.Entity;
			}
			set
			{
				Razas previousValue = this._Razas.Entity;
				if (((previousValue != value) 
							|| (this._Razas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Razas.Entity = null;
						previousValue.ReportesPerdidos.Remove(this);
					}
					this._Razas.Entity = value;
					if ((value != null))
					{
						value.ReportesPerdidos.Add(this);
						this._RazaID = value.RazaID;
					}
					else
					{
						this._RazaID = default(int);
					}
					this.SendPropertyChanged("Razas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_ReportesPerdidos", Storage="_Usuarios", ThisKey="FinderUsuarioID", OtherKey="UsuarioID", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.ReportesPerdidos.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.ReportesPerdidos.Add(this);
						this._FinderUsuarioID = value.UsuarioID;
					}
					else
					{
						this._FinderUsuarioID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_ReportesPerdidos1", Storage="_Usuarios1", ThisKey="ReporterUsuarioID", OtherKey="UsuarioID", IsForeignKey=true)]
		public Usuarios Usuarios1
		{
			get
			{
				return this._Usuarios1.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios1.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios1.Entity = null;
						previousValue.ReportesPerdidos1.Remove(this);
					}
					this._Usuarios1.Entity = value;
					if ((value != null))
					{
						value.ReportesPerdidos1.Add(this);
						this._ReporterUsuarioID = value.UsuarioID;
					}
					else
					{
						this._ReporterUsuarioID = default(int);
					}
					this.SendPropertyChanged("Usuarios1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FotosReportesPerdidos(FotosReportesPerdidos entity)
		{
			this.SendPropertyChanging();
			entity.ReportesPerdidos = this;
		}
		
		private void detach_FotosReportesPerdidos(FotosReportesPerdidos entity)
		{
			this.SendPropertyChanging();
			entity.ReportesPerdidos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SolicitudesAdopcion")]
	public partial class SolicitudesAdopcion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SolicitudID;
		
		private int _UsuarioID;
		
		private int _MascotaID;
		
		private System.DateTime _FechaSolicitud;
		
		private string _Estado;
		
		private System.Nullable<System.DateTime> _FechaAprobacion;
		
		private EntityRef<Mascotas> _Mascotas;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSolicitudIDChanging(int value);
    partial void OnSolicitudIDChanged();
    partial void OnUsuarioIDChanging(int value);
    partial void OnUsuarioIDChanged();
    partial void OnMascotaIDChanging(int value);
    partial void OnMascotaIDChanged();
    partial void OnFechaSolicitudChanging(System.DateTime value);
    partial void OnFechaSolicitudChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnFechaAprobacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaAprobacionChanged();
    #endregion
		
		public SolicitudesAdopcion()
		{
			this._Mascotas = default(EntityRef<Mascotas>);
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SolicitudID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SolicitudID
		{
			get
			{
				return this._SolicitudID;
			}
			set
			{
				if ((this._SolicitudID != value))
				{
					this.OnSolicitudIDChanging(value);
					this.SendPropertyChanging();
					this._SolicitudID = value;
					this.SendPropertyChanged("SolicitudID");
					this.OnSolicitudIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="Int NOT NULL")]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._UsuarioID = value;
					this.SendPropertyChanged("UsuarioID");
					this.OnUsuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MascotaID", DbType="Int NOT NULL")]
		public int MascotaID
		{
			get
			{
				return this._MascotaID;
			}
			set
			{
				if ((this._MascotaID != value))
				{
					if (this._Mascotas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMascotaIDChanging(value);
					this.SendPropertyChanging();
					this._MascotaID = value;
					this.SendPropertyChanged("MascotaID");
					this.OnMascotaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSolicitud", DbType="Date NOT NULL")]
		public System.DateTime FechaSolicitud
		{
			get
			{
				return this._FechaSolicitud;
			}
			set
			{
				if ((this._FechaSolicitud != value))
				{
					this.OnFechaSolicitudChanging(value);
					this.SendPropertyChanging();
					this._FechaSolicitud = value;
					this.SendPropertyChanged("FechaSolicitud");
					this.OnFechaSolicitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAprobacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAprobacion
		{
			get
			{
				return this._FechaAprobacion;
			}
			set
			{
				if ((this._FechaAprobacion != value))
				{
					this.OnFechaAprobacionChanging(value);
					this.SendPropertyChanging();
					this._FechaAprobacion = value;
					this.SendPropertyChanged("FechaAprobacion");
					this.OnFechaAprobacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mascotas_SolicitudesAdopcion", Storage="_Mascotas", ThisKey="MascotaID", OtherKey="MascotaID", IsForeignKey=true)]
		public Mascotas Mascotas
		{
			get
			{
				return this._Mascotas.Entity;
			}
			set
			{
				Mascotas previousValue = this._Mascotas.Entity;
				if (((previousValue != value) 
							|| (this._Mascotas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mascotas.Entity = null;
						previousValue.SolicitudesAdopcion.Remove(this);
					}
					this._Mascotas.Entity = value;
					if ((value != null))
					{
						value.SolicitudesAdopcion.Add(this);
						this._MascotaID = value.MascotaID;
					}
					else
					{
						this._MascotaID = default(int);
					}
					this.SendPropertyChanged("Mascotas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_SolicitudesAdopcion", Storage="_Usuarios", ThisKey="UsuarioID", OtherKey="UsuarioID", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.SolicitudesAdopcion.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.SolicitudesAdopcion.Add(this);
						this._UsuarioID = value.UsuarioID;
					}
					else
					{
						this._UsuarioID = default(int);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UsuarioID;
		
		private string _NombreUsuario;
		
		private System.Data.Linq.Binary _Contraseña;
		
		private string _Email;
		
		private string _Rol;
		
		private System.Data.Linq.Binary _FotoPerfil;
		
		private int _IntentosFallidos;
		
		private string _ClaveTemporal;
		
		private System.Nullable<System.DateTime> _FechaExpiracionTemporal;
		
		private EntitySet<AdopcionesAprobadas> _AdopcionesAprobadas;
		
		private EntitySet<ReportesPerdidos> _ReportesPerdidos;
		
		private EntitySet<ReportesPerdidos> _ReportesPerdidos1;
		
		private EntitySet<SolicitudesAdopcion> _SolicitudesAdopcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsuarioIDChanging(int value);
    partial void OnUsuarioIDChanged();
    partial void OnNombreUsuarioChanging(string value);
    partial void OnNombreUsuarioChanged();
    partial void OnContraseñaChanging(System.Data.Linq.Binary value);
    partial void OnContraseñaChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnRolChanging(string value);
    partial void OnRolChanged();
    partial void OnFotoPerfilChanging(System.Data.Linq.Binary value);
    partial void OnFotoPerfilChanged();
    partial void OnIntentosFallidosChanging(int value);
    partial void OnIntentosFallidosChanged();
    partial void OnClaveTemporalChanging(string value);
    partial void OnClaveTemporalChanged();
    partial void OnFechaExpiracionTemporalChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaExpiracionTemporalChanged();
    #endregion
		
		public Usuarios()
		{
			this._AdopcionesAprobadas = new EntitySet<AdopcionesAprobadas>(new Action<AdopcionesAprobadas>(this.attach_AdopcionesAprobadas), new Action<AdopcionesAprobadas>(this.detach_AdopcionesAprobadas));
			this._ReportesPerdidos = new EntitySet<ReportesPerdidos>(new Action<ReportesPerdidos>(this.attach_ReportesPerdidos), new Action<ReportesPerdidos>(this.detach_ReportesPerdidos));
			this._ReportesPerdidos1 = new EntitySet<ReportesPerdidos>(new Action<ReportesPerdidos>(this.attach_ReportesPerdidos1), new Action<ReportesPerdidos>(this.detach_ReportesPerdidos1));
			this._SolicitudesAdopcion = new EntitySet<SolicitudesAdopcion>(new Action<SolicitudesAdopcion>(this.attach_SolicitudesAdopcion), new Action<SolicitudesAdopcion>(this.detach_SolicitudesAdopcion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this.OnUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._UsuarioID = value;
					this.SendPropertyChanged("UsuarioID");
					this.OnUsuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this.OnNombreUsuarioChanging(value);
					this.SendPropertyChanging();
					this._NombreUsuario = value;
					this.SendPropertyChanged("NombreUsuario");
					this.OnNombreUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarBinary(256) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoPerfil", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FotoPerfil
		{
			get
			{
				return this._FotoPerfil;
			}
			set
			{
				if ((this._FotoPerfil != value))
				{
					this.OnFotoPerfilChanging(value);
					this.SendPropertyChanging();
					this._FotoPerfil = value;
					this.SendPropertyChanged("FotoPerfil");
					this.OnFotoPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntentosFallidos", DbType="Int NOT NULL")]
		public int IntentosFallidos
		{
			get
			{
				return this._IntentosFallidos;
			}
			set
			{
				if ((this._IntentosFallidos != value))
				{
					this.OnIntentosFallidosChanging(value);
					this.SendPropertyChanging();
					this._IntentosFallidos = value;
					this.SendPropertyChanged("IntentosFallidos");
					this.OnIntentosFallidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaveTemporal", DbType="VarChar(100)")]
		public string ClaveTemporal
		{
			get
			{
				return this._ClaveTemporal;
			}
			set
			{
				if ((this._ClaveTemporal != value))
				{
					this.OnClaveTemporalChanging(value);
					this.SendPropertyChanging();
					this._ClaveTemporal = value;
					this.SendPropertyChanged("ClaveTemporal");
					this.OnClaveTemporalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaExpiracionTemporal", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaExpiracionTemporal
		{
			get
			{
				return this._FechaExpiracionTemporal;
			}
			set
			{
				if ((this._FechaExpiracionTemporal != value))
				{
					this.OnFechaExpiracionTemporalChanging(value);
					this.SendPropertyChanging();
					this._FechaExpiracionTemporal = value;
					this.SendPropertyChanged("FechaExpiracionTemporal");
					this.OnFechaExpiracionTemporalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_AdopcionesAprobadas", Storage="_AdopcionesAprobadas", ThisKey="UsuarioID", OtherKey="UsuarioID")]
		public EntitySet<AdopcionesAprobadas> AdopcionesAprobadas
		{
			get
			{
				return this._AdopcionesAprobadas;
			}
			set
			{
				this._AdopcionesAprobadas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_ReportesPerdidos", Storage="_ReportesPerdidos", ThisKey="UsuarioID", OtherKey="FinderUsuarioID")]
		public EntitySet<ReportesPerdidos> ReportesPerdidos
		{
			get
			{
				return this._ReportesPerdidos;
			}
			set
			{
				this._ReportesPerdidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_ReportesPerdidos1", Storage="_ReportesPerdidos1", ThisKey="UsuarioID", OtherKey="ReporterUsuarioID")]
		public EntitySet<ReportesPerdidos> ReportesPerdidos1
		{
			get
			{
				return this._ReportesPerdidos1;
			}
			set
			{
				this._ReportesPerdidos1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_SolicitudesAdopcion", Storage="_SolicitudesAdopcion", ThisKey="UsuarioID", OtherKey="UsuarioID")]
		public EntitySet<SolicitudesAdopcion> SolicitudesAdopcion
		{
			get
			{
				return this._SolicitudesAdopcion;
			}
			set
			{
				this._SolicitudesAdopcion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AdopcionesAprobadas(AdopcionesAprobadas entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_AdopcionesAprobadas(AdopcionesAprobadas entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
		
		private void attach_ReportesPerdidos(ReportesPerdidos entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_ReportesPerdidos(ReportesPerdidos entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
		
		private void attach_ReportesPerdidos1(ReportesPerdidos entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios1 = this;
		}
		
		private void detach_ReportesPerdidos1(ReportesPerdidos entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios1 = null;
		}
		
		private void attach_SolicitudesAdopcion(SolicitudesAdopcion entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_SolicitudesAdopcion(SolicitudesAdopcion entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vacunas")]
	public partial class Vacunas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VacunaID;
		
		private int _MascotaID;
		
		private string _NombreVacuna;
		
		private System.DateTime _FechaVacuna;
		
		private EntityRef<Mascotas> _Mascotas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVacunaIDChanging(int value);
    partial void OnVacunaIDChanged();
    partial void OnMascotaIDChanging(int value);
    partial void OnMascotaIDChanged();
    partial void OnNombreVacunaChanging(string value);
    partial void OnNombreVacunaChanged();
    partial void OnFechaVacunaChanging(System.DateTime value);
    partial void OnFechaVacunaChanged();
    #endregion
		
		public Vacunas()
		{
			this._Mascotas = default(EntityRef<Mascotas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VacunaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VacunaID
		{
			get
			{
				return this._VacunaID;
			}
			set
			{
				if ((this._VacunaID != value))
				{
					this.OnVacunaIDChanging(value);
					this.SendPropertyChanging();
					this._VacunaID = value;
					this.SendPropertyChanged("VacunaID");
					this.OnVacunaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MascotaID", DbType="Int NOT NULL")]
		public int MascotaID
		{
			get
			{
				return this._MascotaID;
			}
			set
			{
				if ((this._MascotaID != value))
				{
					if (this._Mascotas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMascotaIDChanging(value);
					this.SendPropertyChanging();
					this._MascotaID = value;
					this.SendPropertyChanged("MascotaID");
					this.OnMascotaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreVacuna", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreVacuna
		{
			get
			{
				return this._NombreVacuna;
			}
			set
			{
				if ((this._NombreVacuna != value))
				{
					this.OnNombreVacunaChanging(value);
					this.SendPropertyChanging();
					this._NombreVacuna = value;
					this.SendPropertyChanged("NombreVacuna");
					this.OnNombreVacunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaVacuna", DbType="Date NOT NULL")]
		public System.DateTime FechaVacuna
		{
			get
			{
				return this._FechaVacuna;
			}
			set
			{
				if ((this._FechaVacuna != value))
				{
					this.OnFechaVacunaChanging(value);
					this.SendPropertyChanging();
					this._FechaVacuna = value;
					this.SendPropertyChanged("FechaVacuna");
					this.OnFechaVacunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mascotas_Vacunas", Storage="_Mascotas", ThisKey="MascotaID", OtherKey="MascotaID", IsForeignKey=true)]
		public Mascotas Mascotas
		{
			get
			{
				return this._Mascotas.Entity;
			}
			set
			{
				Mascotas previousValue = this._Mascotas.Entity;
				if (((previousValue != value) 
							|| (this._Mascotas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mascotas.Entity = null;
						previousValue.Vacunas.Remove(this);
					}
					this._Mascotas.Entity = value;
					if ((value != null))
					{
						value.Vacunas.Add(this);
						this._MascotaID = value.MascotaID;
					}
					else
					{
						this._MascotaID = default(int);
					}
					this.SendPropertyChanged("Mascotas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
